-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 15:27:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ajuda_quem_faz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ajuda_quem_faz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ajuda_quem_faz` DEFAULT CHARACTER SET utf8 ;
USE `db_ajuda_quem_faz` ;

-- -----------------------------------------------------
-- Table `db_ajuda_quem_faz`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ajuda_quem_faz`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `sobre` VARCHAR(500) NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ajuda_quem_faz`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ajuda_quem_faz`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_servico` VARCHAR(255) NOT NULL,
  `setor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ajuda_quem_faz`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ajuda_quem_faz`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `tb_usuario_id_usuario` BIGINT NOT NULL,
  `tb_categoria_id_categoria` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `tb_usuario_id_usuario`, `tb_categoria_id_categoria`),
  INDEX `fk_tb_produto_tb_usuario_idx` (`tb_usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categoria1_idx` (`tb_categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_usuario`
    FOREIGN KEY (`tb_usuario_id_usuario`)
    REFERENCES `db_ajuda_quem_faz`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`tb_categoria_id_categoria`)
    REFERENCES `db_ajuda_quem_faz`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
